version: "3"

networks:
  laravel:

services:

  nginx:
    image: nginx
    restart: always
    container_name: teknasyon_nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/usr/share/nginx/html
    ports:
      - "8080:80"
    networks:
      - laravel

  php:
    build: ./src
    restart: always
    container_name: teknasyon_php
    expose:
      - "9000"
    links:
      - mysql
      - redis
    volumes:
      - ./src:/usr/share/nginx/html
    networks:
      - laravel
  mysql:
    image: mysql:5.7.22
    container_name: teknasyon_mysql
    restart: unless-stopped
    tty: true
    ports:
        - "3306:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
  redis:
    image: redis
    restart: always
    container_name: teknasyon_redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes
    networks:
      - laravel
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: teknasyon_phpmyadmin
    networks:
      - laravel
    ports:
      - "8081:80"
    restart: always
    links:
      - mysql:db
    depends_on:
      - mysql
